### ISSUE TITLE
Virtual memory explosion on 1.5.0

### ISSUE THREAD

**Issue by AltGr** [mirage/ocaml-git#90]
See https://github.com/AltGr/opam-ci/issues/1 for details. 1.4.1 doesn't exhibit this behaviour (although it seems more greedy on resident memory and quite slower).
### 1.4.11, Git_unix.FS, fetch

![opam-ci-fetch-141](https://cloud.githubusercontent.com/assets/807966/8348065/87b092c6-1b49-11e5-9019-1ca5c08f7430.png)

The first peak happens during fetch.

The [ocp-memprof](http://memprof.typerex.org/users/464527645bfe7266d83e8f3c716f1090/2015-06-25_08-14-40_df91f2a4e258e9ba34c1301b85202560_644/index.html) profile is after GC and more interesting when considering resident (heap) memory (the x axis is GC number, not time, the peak corresponds to the fetch).
### 1.5.0, Git_unix.FS, fetch

![opam-ci-fetch-150](https://cloud.githubusercontent.com/assets/807966/8348090/c3793dbc-1b49-11e5-8ec1-70546cc0f08b.png)

The [ocp-memprof](http://memprof.typerex.org/users/464527645bfe7266d83e8f3c716f1090/2015-06-25_08-22-44_a379fbe9dc2da7eb72e59975809f7c82_1587/index.html) profile is also informative. Fetch is'nt changed at all, but the following treatment is faster and takes much lest memory (running once the repo has been fetched to disk is thus much cheaper).
### 1.4.11, Git.Memory, fetch

![opam-ci-mem-141](https://cloud.githubusercontent.com/assets/807966/8348195/1aa0ba56-1b4b-11e5-93f2-cfdd1f1ea864.png)

Fails after the fetch with `Failure("Git_memory.write_pack")`. Same behaviour with 1.5.0.
### 1.4.11, Git_unix.FS, fetch ~unpack:true

![opam-ci-unpack-141](https://cloud.githubusercontent.com/assets/807966/8348297/bc525886-1b4c-11e5-88c0-fe9d746d49d4.png)

First peak is the fetch. Then the mountain is the unpacking process: seems there is stuff that's held until the end and should be cleaned up. The number of open FDs may also be of concern.
This also doesn't seem to change much between 1.4.11 and 1.5.0

Also, after unpacking I couldn't find the commit-hash I was looking for and the program aborted.

---

The last two may deserve their own issues.
To reproduce, you may use the [`testing-git` branch of opam-ci](https://github.com/AltGr/opam-ci/tree/testing-git) which disables normal behaviour and reporting and justs runs a batch fetch. You'll need to pin opam-lib to its latest dev. The function causing the huge virtual memory allocations is [RepoGit.opam_files](https://github.com/AltGr/opam-ci/blob/c0b5ec19365afa328fa3004fbb46da282f12cb9a/opam_ci.ml#L153-L184), which just recursively reads the directory structure at a given commit.

Also, my tests on 1.4.11 actually include a backport of some of the 1.5.0 branch, most importantly, latest cohttp compatibility. See https://github.com/AltGr/ocaml-git/tree/1.5.0-partial-revert

Hope this helps.

**Comment by AltGr** [comment]
Ah, and if you're interested in the dumb little script I used for the memory graphs, it's [here](https://gist.github.com/AltGr/ac942cfe7314129090be). I ran it with `-i 0.1`.

**Comment by AltGr** [comment]
Note that I used `fetch` directly, without cloning first. It seemed equivalent to me, but maybe that's wrong.

**Comment by samoht** [comment]
If you have any chance to dig the issue a bit more that would be *very* helpful. I think it's just a matter of adding @chambart's caching functions of at the right place in the new pack code.

**Comment by samoht** [comment]
I think I've found the issue. It would be very nice to have an automated test exhibiting the issue ...

**Comment by samoht** [comment]
Re-opening because of https://github.com/mirage/ocaml-git/pull/93#issuecomment-118461469

**Comment by samoht** [comment]
A workaround is to use `~depth:1` and `Git.Memory.clear_all` before every clone. It's possible that `Sync.fetch` still download and fetch big pack files which needs to be kept in memory, which would exlain why the memory is increasing over time.

**Comment by AltGr** [comment]
you mean `Sync.fetch ~deepen:1` ? With the current setup it won't work, as we use the history to find the merge-base (aka closest common ancestor) ; we could make do by fetching github's merge commit and doing the checks on that, though.

`Git.Memory.clear_all` alone doesn't seem to change the memory profile much.

**Comment by samoht** [comment]
> Git.Memory.clear_all alone doesn't seem to change the memory profile much.

This is very weird. I'd be very interested to understand more about that leak but I have currently no idea where it could come from ...

**Comment by AltGr** [comment]
Just tested with `~unpack` -- which is fixed, it seems :) -- and all problems go away. So it must be somewhere in the pack-handling code.

From what I could gather, the various caches contain very few elements in the packed case (I did some digging around and LRU seems to remain of size 1 or 2), so it must be that the elements themselves are kept but start holding bigger and bigger structures inside ?

**Comment by AltGr** [comment]
Now running @camelus with ~unpack on the server. The first fetch took forever (the unpack operation is still extremely memory greedy, and there wasn't enough memory for both file caches and datastructures) -- but it barely passed, and memory usage is now completely fine.

**Comment by samoht** [comment]
great! `ocaml-git` master has already some optmization to reduce allocations when handling pack files, I'm sure more things can be improved. It's still not totally clear to me why `~unpack:false` leaks memory, but at least we know where to look now. Thanks for investigating!

**Comment by samoht** [comment]
1.7.0 should be much more efficient regarding memory consumption after synchronisation: the first `clone` should be much more efficient and subsequent `fetch` will now only download the minimal pack file. If you could test more to check that's indeed ok that could be great!

**Comment by AltGr** [comment]
Awesome, I'll run my benches on that and report as soon as I get the time :)

**Comment by Chris00** [comment]
May this be related to https://github.com/mirage/irmin/issues/263 ?

**Comment by samoht** [comment]
Should be fixed in ocaml-git 2.0
